### ISSUE TITLE
TypeError related to strawberry in 6.3.2

### ISSUE THREAD

**Issue by anthu** [kedro-org/kedro-viz#1442]
## Description
With the upgrade to 6.3.2 I'm experiencing a TypeError as following:
`TypeError: union() missing 1 required positional argument: 'types'`

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
```
# Good
python -m pip install -U kedro-viz==6.3.1
python -m kedro viz

# Bad
python -m pip install -U kedro-viz==6.3.2
python -m kedro viz
```

## Expected Result
Kedro Viz should run

## Actual Result
```
TypeError: union() missing 1 required positional argument: 'types'
```

### Full Stack Trace
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro/__main__.py", line 10, in <module>
    main()
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro/framework/cli/cli.py", line 211, in main
    cli_collection()
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro/framework/cli/cli.py", line 139, in main
    super().main(
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/launchers/cli.py", line 86, in viz
    from kedro_viz.server import is_localhost, run_server
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/server.py", line 13, in <module>
    from kedro_viz.api import apps
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/api/apps.py", line 19, in <module>
    from .graphql.router import router as graphql_router
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/api/graphql/router.py", line 5, in <module>
    from .schema import schema
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/api/graphql/schema.py", line 23, in <module>
    from .serializers import (
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/api/graphql/serializers.py", line 15, in <module>
    from .types import Run
  File "/usr/local/Caskroom/miniconda/base/envs/kedro-environment/lib/python3.10/site-packages/kedro_viz/api/graphql/types.py", line 73, in <module>
    strawberry.union(
TypeError: union() missing 1 required positional argument: 'types'
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version: MacOS 13.4.1 (Intel)
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 0.18.11
* Python version used (if relevant): Python 3.10.11

```
> python -m pip freeze
aiofiles==22.1.0
aiosqlite==0.19.0
antlr4-python3-runtime==4.9.3
anyconfig==0.10.1
anyio==3.7.0
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asn1crypto==1.5.1
asttokens==2.2.1
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
binaryornot==0.4.4
black==22.12.0
bleach==6.0.0
build==0.10.0
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.0.0
comm==0.1.3
cookiecutter==2.1.1
coverage==7.2.7
cryptography==40.0.2
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
dynaconf==3.1.12
exceptiongroup==1.1.1
executing==1.2.0
fastapi==0.95.2
fastjsonschema==2.17.1
filelock==3.12.2
flake8==3.9.2
fqdn==1.5.1
fsspec==2023.6.0
gitdb==4.0.10
GitPython==3.1.31
graphql-core==3.2.3
greenlet==2.0.2
h11==0.14.0
httptools==0.5.0
idna==3.4
importlib-metadata==6.7.0
importlib-resources==5.12.0
iniconfig==2.0.0
ipykernel==6.23.3
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==8.0.6
isoduration==20.11.0
isort==5.12.0
jedi==0.18.2
Jinja2==3.1.2
jinja2-time==0.2.0
jmespath==0.10.0
json5==0.9.14
jsonpointer==2.4
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-ydoc==0.2.4
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.6.0
jupyter_server_fileid==0.9.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.4
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.23.0
kedro==0.18.11
kedro-datasets==1.4.1
kedro-telemetry==0.2.4
kedro-viz==6.3.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mccabe==0.6.1
mdurl==0.1.2
mistune==3.0.1
more-itertools==9.1.0
mypy-extensions==1.0.0
nbclassic==1.0.0
nbclient==0.8.0
nbconvert==7.6.0
nbformat==5.9.0
nbstripout==0.6.1
nest-asyncio==1.5.6
networkx==3.1
notebook==6.5.4
notebook_shim==0.2.3
numpy==1.25.0
omegaconf==2.3.0
orjson==3.9.1
oscrypto==1.3.0
overrides==7.3.1
packaging==23.1
pandas==2.0.2
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.1
pexpect==4.8.0
pickleshare==0.7.5
pip-tools==6.13.0
platformdirs==3.8.0
plotly==5.15.0
pluggy==1.0.0
prometheus-client==0.17.0
prompt-toolkit==3.0.38
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pycodestyle==2.7.0
pycparser==2.21
pycryptodomex==3.18.0
pydantic==1.10.9
pyflakes==2.3.1
Pygments==2.15.1
PyJWT==2.7.0
pyOpenSSL==23.2.0
pyproject_hooks==1.0.0
pyrsistent==0.19.3
pytest==7.4.0
pytest-cov==3.0.0
pytest-mock==1.13.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-slugify==8.0.1
pytoolconfig==1.2.5
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.4.2
rope==1.8.0
secure==0.3.0
semver==3.0.1
Send2Trash==1.8.2
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
snowflake-connector-python==3.0.4
snowflake-snowpark-python==1.5.1
sortedcontainers==2.4.0
soupsieve==2.4.1
SQLAlchemy==2.0.17
stack-data==0.6.2
starlette==0.27.0
strawberry-graphql==0.189.0
tenacity==8.2.2
terminado==0.17.1
text-unidecode==1.3
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
toposort==1.10
tornado==6.3.2
traitlets==5.9.0
typing_extensions==4.6.3
tzdata==2023.3
uri-template==1.3.0
urllib3==1.26.16
uvicorn==0.22.0
uvloop==0.17.0
watchfiles==0.19.0
watchgod==0.8.2
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
websockets==11.0.3
widgetsnbextension==4.0.7
y-py==0.5.9
ypy-websocket==0.8.2
zipp==3.15.0
```

## Checklist
- [X] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment]
Hi @anthu , see #1441. You might need to upgrade strawberry-graphql

**Comment by anthu** [comment]
Thanks,
works with force-updating `strawberry-graphql` to >= 0.192.0
