### ISSUE TITLE
conf-source param 

### ISSUE THREAD

**Issue by m-gris** [kedro-org/kedro-viz#1479]
Hi, 

It would be really handy and bring quite bit of flexibility if `kedro viz` could accept a `conf-source` argument.  

As "rhetorical precaution", I must admit that this request is motivated by a bit of an un-usual way of organization our conf: We have a single pipeline / repo for all our clients and it seemed to us that the following organization of `conf` and `data` would be "safer" and provide a better "tenant isolation" (it also avoids issues such as duplicated keys in the clients' parameter files): 

```
conf
└── client_A
    ├── base
    └── local
└── client_B
    ├── base
    └── local
data
├── client_A
│   └── 01_raw
│   └── 02_intermediate
│   └── ...
└── client_B
│   └── 01_raw
│   └── 02_intermediate
│   └── ...
```

I hope that, in spite of the idiosyncratic nature of the above, you will consider this request as relevant.  

Many thanks in advance, 
Regards, 
M.

**Comment by m-gris** [comment]
Thx yetudada for your message.  

Unfortunately, given the way I've organized the conf,  the `--env` flag does work. 

Bother `kedro viz --env client_a` and `kedro viz --env client_a/base` result in 

```
kedro viz --env client_a
Traceback (most recent call last):
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro_viz/launchers/cli.py", line 134, in viz
    run_server(**run_server_kwargs)
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro_viz/server.py", line 83, in run_server
    catalog, pipelines, session_store = kedro_data_loader.load_data(
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro_viz/integrations/kedro/data_loader.py", line 81, in load_data
    with KedroSession.create(
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/framework/session/session.py", line 194, in create
    session._setup_logging()
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/framework/session/session.py", line 212, in _setup_logging
    logging_config = self._get_logging_config()
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/framework/session/session.py", line 201, in _get_logging_config
    logging_config = self._get_config_loader()["logging"]
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/framework/session/session.py", line 293, in _get_config_loader
    return config_loader_class(
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/config/templated_config.py", line 138, in __init__
    _get_config_from_patterns(
  File "/home/vscode/.pyenv/versions/3.10.7/envs/kedro_dodo_ingestion/lib/python3.10/site-packages/kedro/config/common.py", line 73, in _get_config_from_patterns
    raise ValueError(
ValueError: Given configuration path either does not exist or is not a valid directory: /workspaces/kedro-dodo-ingestion/conf/base
kedro.framework.cli.utils.KedroCliError: Given configuration path either does not exist or is not a valid directory: /workspaces/kedro-dodo-ingestion/conf/base
Run with --verbose to see the full exception
Error: Given configuration path either does not exist or is not a valid directory: /workspaces/kedro-dodo-ingestion/conf/base
```

**Comment by astrojuanlu** [comment]
xref https://github.com/kedro-org/kedro-plugins/issues/672 (different target, similar functionality)

**Comment by ravi-kumar-pilla** [comment]
Given that kedro-viz is a read-only representation of your Kedro project, it would be confusing having a different conf-source in your kedro project and kedro-viz. For now, we would like to read conf-source from kedro. However if there are more requests regarding this, the team would look into this. Thank you
