### ISSUE TITLE
Kedro Viz stays waiting even if no valid project was found

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1761]
## Description
I accidentally launched Kedro Viz from the wrong directory and this is what I got:

```
kedro viz run
Starting Kedro Viz ...
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc/.venv/lib/python3.11/site-packages/kedro_viz/server.py", line 110, in run_server
    load_and_populate_data(path, env, ignore_plugins, extra_params, pipeline_name)
  File "/Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc/.venv/lib/python3.11/site-packages/kedro_viz/server.py", line 60, in load_and_populate_data
    catalog, pipelines, session_store, stats_dict = kedro_data_loader.load_data(
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc/.venv/lib/python3.11/site-packages/kedro_viz/integrations/kedro/data_loader.py", line 109, in load_data
    bootstrap_project(project_path)
  File "/Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc/.venv/lib/python3.11/site-packages/kedro/framework/startup.py", line 162, in bootstrap_project
    metadata = _get_project_metadata(project_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc/.venv/lib/python3.11/site-packages/kedro/framework/startup.py", line 68, in _get_project_metadata
    raise RuntimeError(
RuntimeError: Could not find the project configuration file 'pyproject.toml' in /Users/juan_cano/Projects/QuantumBlackLabs/brix-posts/posts/kedro-viz-chatbot-tbc. If you have created your project with Kedro version <0.17.0, make sure to update your project template. See https://github.com/kedro-org/kedro/blob/main/RELEASE.md#migration-guide-from-kedro-016-to-kedro-0170 for how to migrate your Kedro project.

```

...and it kept hanging there.

It would be nice if, in this case, it would immediately exit, since otherwise it gives the wrong impression that Kedro Viz is still serving something.

```

^C
Aborted!
```

(Cmd-C to cancel worked as expected)

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version:
* Operating system and version:
* NodeJS version used (if relevant):
* Kedro version used (if relevant): 0.19.2
* Python version used (if relevant): 7.1.0

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment]
Related: https://github.com/kedro-org/kedro/issues/1829, https://github.com/kedro-org/kedro/issues/1831

**Comment by astrojuanlu** [comment]
cc @noklam @ankatiyar
